### ISSUE TITLE
[Question] I'm not sure where else I'd be able to ask; Does enabling this change any of XIV's base configurations or settings? 

### ISSUE THREAD

**Issue by CrazedSadeyr** [Sevii77/frost_ui#13]
I'm wanting to try Frost UI out and see how it feels, but I'm afraid of my base stuff (hud, configurations, settings, etc) being changed.  Does FrostUI affect any of that, or is it isolated so if I enable then disable the stuff will return to how it was?  Thank you!

**Comment by ShichiIzanagi** [comment]
Its essentially just a skin, it wont touch any of that - only visually.

**Comment by CrazedSadeyr** [comment]
Thank you for the info! <3
