### ISSUE TITLE
Compass Icons appear to be misaligned

### ISSUE THREAD

**Issue by zbee** [Sevii77/frost_ui#5]
As you can see from the images below it does not seem like the cardinal directions' offsets are quite right, leading to them appearing misaligned - some closer to each other than others, others not aligned to the center marker. West is particularly egregious.

North is alright, East is good; but South is off, and West is way off.

<img src="https://github.com/user-attachments/assets/cbd63011-3f04-4a6a-b032-e7fdd6713251" style="width:49%" />
<img src="https://github.com/user-attachments/assets/0d97b615-7932-41d0-a1cf-70b91f69f0b1" style="width:49%" />
<img src="https://github.com/user-attachments/assets/a2254306-e756-4389-99d6-193c9a4b39d4" style="width:49%" />
<img src="https://github.com/user-attachments/assets/d7cfde04-c224-4d33-9c72-dea2c6e62103" style="width:49%" />

![image](https://github.com/user-attachments/assets/f54cc9c2-5c40-4133-96f0-150d5090acfc)

[I also opened a bug on my compass](https://github.com/fitzchivalrik/compass/issues/26), as the cardinal icons in Frost UI *look* right, but there's no way for me to tell.

**Comment by Sevii77** [comment]
The cardinal icons are laid out that way to make it look nice on the navimap. The best solution would be for compass to center the loaded icons based on visible pixels, that would make it compatible with other ui mods aswell.

Frost UI icons compared to vanilla:
![image](https://github.com/user-attachments/assets/c7252ddd-a6aa-48f8-b311-42bdbd50314e)
