### ISSUE TITLE
[Installation] Not sure about the process

### ISSUE THREAD

**Issue by NokodaTsu** [Sevii77/frost_ui#7]
Hai :) Hope this doesn't come as an annoyance but I'm not sure if I'm doing it right, since I can't get FrostUI to work it seems.

After getting Aetherment, you just have to go in "Browser", select the last version of FrostUI, click instal and restart the game or is there another step I'm missing ?

It did create a folder in my game one but not sure what to do with this after that part 🙏

**Comment by RaidenvBlack** [comment]
Activate the FrostUI Mod in Penumbra

**Comment by NokodaTsu** [comment]
Oh I see! Alrighty thanks :)

**Comment by fafshari** [comment]
Penumbra should be listed as a dependency in the Readme

**Comment by yulexiv** [comment]
> Activate the FrostUI Mod in Penumbra

I don't understand... where do I get the mod?

**Comment by RaidenvBlack** [comment]
When you install it in Aetherment. For more informations just join the Discord server in the Readme
