### ISSUE TITLE
[Request] Party List BG

### ISSUE THREAD

**Issue by nolnoch** [Sevii77/frost_ui#9]
The current Party List background in both MaterialUI and FrostUI presets is 100% transparent, and I can't find a way to change it. Would it be possible to add a Party List Background RGBA and/or texture selector? The Glow-style job icons look great but can be hard to see over 100% transparency.

I found the json-style config locally in the Roaming/Aetherment folder, but it doesn't appear to offer that option, and I'm not familiar enough with Rust to suggest a tweak to the mod myself. I did find "PartyList_Bg_hr1.tex" and the "partylist_bg.svg" that references it in the repo, so it looks like there's intent to have a background, but it's not being used as far as I can tell.

Thank you for the mod, and let me know if I can help!

**Comment by ShichiIzanagi** [comment]
![grafik](https://github.com/user-attachments/assets/27357f9a-67fb-4942-a4cd-ed02c4e49dcc)
Known - from the discord known issues channel. Will be implemented.

**Comment by Sevii77** [comment]
Added in 69c8880e0ffb92bfc17cbb0edcc24ae2760eb139
